#!/bin/sh
cliphist list | awk '{$1=""; $2=""; print $0}' | bemenu --tb "#000000" --fb "#000000" --cb "#000000" --nb "#000000" --hb "#000000" --sb "#000000" --fbb "#000000" --ab "#000000" --scb "#000000" --nf "#FFFFFF" --ff "#FFFFFF" --tf "#FFFFFF" --sf "#2149b4" --hf "#40C4FF" --no-overlap --bottom --fn 'JetBrainsMono Nerd Font 12' "$@" | cliphist decode | wl-copy
